[2024-04-08 03:00:17,816: INFO: main: Custom Log]
[2024-04-08 23:24:39,169: INFO: main: Custom Log]
[2024-04-08 23:48:33,191: INFO: main: Custom Log]
[2024-04-09 02:22:29,960:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 02:22:29,977:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 02:22:29,980:INFO:common:created directory at: artifacts]
[2024-04-09 02:22:29,983:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 02:22:29,989:INFO:986331348:Downloading data from https://drive.google.com/file/d/1_NwVT-xSB9j-kRqtot_zQFD134792qyf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-09 02:23:00,546:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1_NwVT-xSB9j-kRqtot_zQFD134792qyf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-09 02:47:49,518:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-09 02:47:49,524:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 02:47:49,526:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 02:47:49,528:INFO:common:created directory at: artifacts]
[2024-04-09 02:47:49,529:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 02:47:50,315:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Mon, 08 Apr 2024 21:17:50 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=oiB-0J0bNRjLOfhO63Q-4KqWgLzbP2_XP_5GdO-VvhxfmSgUWvNZQzeJe5BI1XJPeXkkF4xFbGmp8RI6gyo6t12O5sfXwj00WSK62JJQyhLdkhRBuPZ5t08BTxWlfdRKQKM7V50-ZKWsqBdC_Kkt8siMp19meo6Yma2c68OrD3E; expires=Tue, 08-Oct-2024 21:17:50 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-09 02:47:50,689:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "C:\Users\91910\anaconda3\lib\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\91910\anaconda3\lib\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\91910\anaconda3\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\91910\anaconda3\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-09 03:04:56,944:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-09 03:04:56,947:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 03:04:56,948:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 03:04:56,949:INFO:common:created directory at: artifacts]
[2024-04-09 03:04:56,949:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 03:04:57,835:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Mon, 08 Apr 2024 21:34:57 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=Tmq5WRJcEBAFjPruGIHXt3P5hrx29W2S2pyfZaEyc05LMHrYYK43kqtqJFofaHMJs5XXRSGapR48vMe0LcH3j1FBHtFTJpEsvNzl5R05pVLdWmYaR1jqBVk2k6ToWqiWx7yhX5XBpwZ-R5OdNa10zk-tPG8oXQMXHrF-obZUYrU; expires=Tue, 08-Oct-2024 21:34:57 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-09 03:04:57,981:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "C:\Users\91910\anaconda3\lib\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\91910\anaconda3\lib\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\91910\anaconda3\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\91910\anaconda3\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-09 03:33:28,831:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-09 03:33:28,847:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 03:33:28,849:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 03:33:28,850:INFO:common:created directory at: artifacts]
[2024-04-09 03:33:28,850:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 03:33:28,850:INFO:data_ingestion:File already exists of size: ~ 83 KB]
[2024-04-09 03:33:28,850:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    obj.main()
  File "C:\Users\91910\anaconda3\lib\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\91910\anaconda3\lib\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\91910\anaconda3\lib\zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "C:\Users\91910\anaconda3\lib\zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-09 03:48:13,870: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-09 03:48:13,884: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-09 03:48:13,886: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-09 03:48:13,886: INFO: common: created directory at: artifacts]
[2024-04-09 03:48:13,887: INFO: common: created directory at: artifacts/data_ingestion]
[2024-04-09 03:48:13,888: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1_NwVT-xSB9j-kRqtot_zQFD134792qyf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-09 03:48:34,359: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1_NwVT-xSB9j-kRqtot_zQFD134792qyf/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-09 03:48:46,770: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
